def readme(profile: str, pwa_mode: str, app_title: str) -> str:
    fullstack_block = ""
    if profile == "fullstack-render":
        fullstack_block = """
## Backend (fullstack profile)

Start backend in a separate terminal:

```bash
npm run backend:dev
```

Prisma helpers:

```bash
npm run db:generate
npm run db:migrate
```
"""

    return apply_tokens(
        """# __APP_TITLE__

Scaffold generated by `logics-react-render-pwa-bootstrapper`.

## Stack

- React 19 + Vite + TypeScript strict
- PWA mode: `__PWA_MODE__`
- Profile: `__PROFILE__`
- ESLint + Vitest + Playwright
- Render blueprint in `render.yaml`

## Local setup

```bash
npm ci
npm run dev
```

## Quality gates

```bash
npm run lint
npm run typecheck
npm run test:ci
npm run test:e2e
npm run build
npm run quality:pwa
```

Run everything in one command:

```bash
npm run ci:local
```

__FULLSTACK_BLOCK__
## Render deploy

- Frontend-only profile: deploy static service from this repository root.
- Fullstack profile: use generated multi-service `render.yaml` and replace placeholder host values.
""",
        {
            "APP_TITLE": app_title,
            "PWA_MODE": pwa_mode,
            "PROFILE": profile,
            "FULLSTACK_BLOCK": fullstack_block,
        },
    )


def test_setup() -> str:
    return """import "@testing-library/jest-dom/vitest";
"""


def app_test() -> str:
    return """import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import App from "../App";

describe("App", () => {
  it("renders the app title", () => {
    render(<App />);
    expect(screen.getByRole("heading", { name: /.+/ })).toBeInTheDocument();
  });
});
"""


def pwa_registration_test() -> str:
    return """import { describe, expect, it } from "vitest";
import { registerPwa } from "../pwa/runtime";

describe("PWA registration", () => {
  it("is a safe no-op outside production", async () => {
    expect(import.meta.env.PROD).toBe(false);
    await expect(registerPwa()).resolves.toBeUndefined();
  });
});
"""


def e2e_smoke_test(app_title: str) -> str:
    return apply_tokens(
        """import { expect, test } from "@playwright/test";

test("home screen renders", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "__APP_TITLE__" })).toBeVisible();
});
""",
        {"APP_TITLE": app_title},
    )


